language: java
dist: trusty
sudo: required
jdk:
  - oraclejdk8
addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - mysql
  - postgresql
env:
  - PGPORT=5433
before_install:
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS vagrant;' -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON vagrant.* TO 'vagrant'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
script: mvn clean test
after_success:
  - mvn clean site -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:report
