language: java
dist: xenial
sudo: required
jdk:
  - openjdk8
addons:
    postgresql: 10
    apt:
        packages:
        - postgresql-10-postgis-2.4
services:
  - mysql
  - postgresql
before_install:
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS vagrant;' -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON vagrant.* TO 'vagrant'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  - psql -U postgres -c "CREATE EXTENSION postgis"
script: mvn clean test
after_success:
  - mvn clean site -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:report
