language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8
addons:
    postgresql: 9.3
    apt:
        packages:
        - postgresql-9.3-postgis-2.3
services:
  - mysql
  - postgresql
before_install:
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS vagrant;' -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON vagrant.* TO 'vagrant'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  - psql -U postgres -c "CREATE EXTENSION postgis"
script: mvn clean test
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

