language: java
dist: trusty
sudo: required
jdk:
  - oraclejdk8
addons:
    postgresql: 9.4
    apt:
        packages:
        - postgresql-9.4-postgis-2.3
services:
  - mysql
  - postgresql
before_install:
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS vagrant;' -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON vagrant.* TO 'vagrant'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  - psql -U postgres -c "CREATE EXTENSION postgis"
script: mvn clean test
after_success:
  - mvn clean site -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:report

