language: java
dist: bionic
sudo: required
env:
  - PGPORT=5433
jdk:
  - openjdk8
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - docker
  - mysql
  - postgresql
before_install:
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS vagrant;' -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON vagrant.* TO 'vagrant'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  - sudo cp vmsetup/p*.conf /etc/postgresql/10/main/
  - sudo /etc/init.d/postgresql restart
  - sudo -u postgres psql -c "alter user postgres with password '';"
  - sudo docker pull arafato/azurite
  - mkdir /tmp/azurite
  - sudo docker run -e executable=blob -d -t -p 10000:10000 -v /tmp/azurite:/opt/azurite/folder arafato/azurite
script: mvn clean test
after_success:
  - mvn clean site -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:report
