services:
  mysql:
    image: circleci/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=vagrant
    ports:
      - "3306:3306"
  postgres:
    image: circleci/postgres:10-alpine-postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - TZ=GMT+2
      - PGTZ=GMT+2
    ports:
      - "5432:5432"
  azurite:
    image: arafato/azurite:2.6.5
    ports:
      - 10000:10000
    environment:
      executable: blob
