version: 2.1
orbs:
  maven: circleci/maven@1.2.0
jobs:
  build_and_test:
    docker:
      - image: cimg/base:stable-18.04
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vagrant
      - image: circleci/postgres:10-alpine-postgis
      - image: circleci/openjdk:8u131-jdk
      - image: arafato/azurite
        environment:
          executable: blob
    steps:
      - checkout
      - run:
          name: Install maven
          command: sudo apt-get update && sudo maven
      - run:
          name: Run unit tests
          command: mvn clean test
      - run:
          name: Generate code coverage
          command: mvn clean site -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:report
workflows:
  all:
    jobs:
      - build_and_test
