version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/base:stable-18.04
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vagrant
      - image: circleci/postgres:10-alpine-postgis
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
          TZ: GMT+2
          PGTZ: GMT+2
      - image: maven:3.6-openjdk-8
      - image: arafato/azurite
        environment:
          executable: blob
    steps:
      - checkout
      - run:
          name: Install java / maven
          command: sudo apt-get install -y maven openjdk-8-jdk
      - run:
          name: Maven Unit Tests
          command: mvn -X clean package
      - run:
          name: CLI Tests
          command: tests/bin/testall.sh
      - run:
          name: Generate code coverage
          command: ./make.sh coverage
workflows:
  all:
    jobs:
      - build_and_test
