version: 2.1
orbs:
  maven: circleci/maven@1.2.0
jobs:
  buildimage:
    docker:
      - image: cimg/base:stable-18.04
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vagrant
      - image: circleci/postgres:10-alpine-postgis
      - image: circleci/openjdk:8u131-jdk
      - image: arafato/azurite
        environment:
          executable: blob
    steps:
      - checkout
workflows:
  buildimg:
    jobs:
      - buildimage
  maven_test:
    jobs:
      - maven/test:
  maven_coverall:
    jobs:
      - maven/test:
        command: "clean site -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:report"
