version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/base:stable-18.04
      - image: circleci/mysql:5.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vagrant
      - image: circleci/postgresql:10
    steps:
      - checkout
      - run:
          name: Update repo
          command: sudo apt-get update
      - run:
          name: Install openjdk 8 and maven
          command: sudo apt-get install -y openjdk-8-jdk maven
      - run:
          name: Install postgresql 10
          command: |
            sudo apt-get install -y postgresql-10
            sudo cp vmsetup/p*.conf /etc/postgresql/10/main/
            sudo /etc/init.d/postgresql restart
      - run:
          name: Setup mysql
          command: |
            mysql -e 'CREATE DATABASE IF NOT EXISTS vagrant;' -uroot
            mysql -e "GRANT ALL PRIVILEGES ON vagrant.* TO 'vagrant'@'localhost';" -uroot
      - run:
          name: azurite
          command: |
            sudo docker pull arafato/azurite
            sudo docker run -e executable=blob -d -t -p 10000:10000 -v /tmp/azurite:/opt/azurite/folder arafato/azurite
      - run:
          name: Build and test
          command: mvn clean test
      - run:
          name: Generate code coverage
          command: mvn clean site -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:report
workflows:
  all:
    jobs:
      - build_and_test
