version: 2.1
orbs:
  codecov: codecov/codecov@1.2.3
jobs:
  build_and_test:
    docker:
      - image: maven:3.6.0-jdk-8
        environment:
         TZ: "America/Los_Angeles"
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vagrant
      - image: circleci/postgres:10-alpine-postgis
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
          TZ: 'GMT+2'
      - image: arafato/azurite
        environment:
          executable: blob
    steps:
      - checkout
      - run:
          name: Install hexdump
          command: apt-get update && apt-get install -y bsdmainutils
      - run:
          name: Maven unit tests
          command: mvn clean package
      - run:
          name: CLI unit tests
          command: chmod +x tests/bin/*.sh && tests/bin/testall.sh -j
      - run:
          name: Aggregate code coverage report
          command: mvn jacoco:report-aggregate
      - codecov/upload:
          file: jaqy-codecov/target/site/jacoco-aggregate/jacoco.xml
workflows:
  all:
    jobs:
      - build_and_test
